### ISSUE TITLE
Show available queue resources on queue select form components

### ISSUE THREAD

**Issue by brnovasco** [cnpem/deepsirius-ui#4]
Show information from SLURM about available queues for the logged user and the resource limits and live states for each queue before submitting a new job.

Reference: https://github.com/cnpem/launch3d/pull/2 

![image](https://github.com/user-attachments/assets/e8687c92-4498-4db4-b0cd-88d429f6e426)

**Comment by matyson** [comment]
Closed in 1206719cf02fa54d74002a52bd4fd8aecf573f66
